py_binary(
    name = "embedder",
    srcs = ["embedder.py"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "casfile_url",
    srcs = ["casfile_url.py"],
    visibility = ["//visibility:public"],
)
