apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-server
  name: hello-world-server
spec:
  ports:
  - name: http-server
    port: 80
    targetPort: http-server
  selector:
    app: hello-world-server
