apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-server
  template:
    metadata:
      labels:
        app: hello-world-server
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: hello-world-server
            optional: false
        image: index.docker.io/netchris/hello-world-server@sha256:04f271fe38c4a8c50ace6c4cb5ed211fd86f5053fac8600489bab7c95402cadd
        name: server
        ports:
        - containerPort: 8080
          name: http-server
        terminationMessagePolicy: FallbackToLogsOnError
