load("//terraform:def.bzl", "terraform_provider")

terraform_provider(
    name = "kubectl",
    file = "terraform-provider-kubectl.tpl.sh",
    provider_name = "kubectl",
    version = "v0.3.1",
    visibility = ["//visibility:public"],
)
