load("//terraform:def.bzl", "terraform_plugin")

terraform_plugin(
    name = "kubectl",
    darwin_amd64 = "terraform-provider-kubectl.tpl.sh",
    linux_amd64 = "terraform-provider-kubectl.tpl.sh",
    version = "v0.2.0",
    visibility = ["//visibility:public"],
)
