load("//terraform:def.bzl", "terraform_provider")

terraform_provider(
    name = "kubectl",
    file = "@tool_terraform_provider_kubectl//:file",
    provider_name = "kubectl",
    visibility = ["//visibility:public"],
)
